setwd("~/Documents/workspace/ITES_analysis1")
base_filename = "SEQ_MOOCdb_IFT_Info_Theo_H2016_aF_i5_C105_T300_DF_NEW"
library(TraMineR)
all_data = read.table(file=paste(base_filename,'.txt',sep=''), sep='|', header=T)
all_data = as.data.frame(all_data)
#seq_states <- c("Lo", "Pa", "Pl", "Se", "Sp", "St")
#seq_states <- c("0", "1", "2", "3", "4", "5")
#seq_labels <- c("Lo", "Pa", "Pl", "Se", "Sp", "St")
#full_labels <- c("load_video", "pause_video", "play_video", "seek_video", "speed_change_video", "stop_video")
#seq_states <- c("Lo", "Pa", "Pl", "Sb", "Sf", "Sp", "St")
seq_states <- c("0", "1", "2", "3", "4", "5", "6")
seq_labels <- c("Lo", "Pa", "Pl", "Sb", "Sf", "Sp", "St")
full_labels <- c("load_video", "pause_video", "play_video", "seek_back_video", "seek_forward_video", "speed_change_video", "stop_video")
seq_act = seqdef(all_data, 216:515, states = seq_labels,labels = full_labels,alphabet=seq_states)
seq_act_NA = seqdef(all_data, 216:515, states = seq_labels,labels = full_labels,with.missing=TRUE,void='*',missing.color="white",alphabet=seq_states)
seq_clic = seqdef(all_data, 6:110, states = seq_labels,labels = full_labels,alphabet=seq_states)
seq_clic_NA = seqdef(all_data, 6:110, states = seq_labels,labels = full_labels,with.missing=TRUE,void='*',missing.color="white",alphabet=seq_states)

submat <- seqsubm(seq_clic, method = "CONSTANT", cval = 1)
dist_om1 <- seqdist(seq_clic, method = "OM", indel = 1, sm = submat)
library(cluster)
pamclust3 <- pam(dist_om1,3,diss=TRUE)
pamclust4 <- pam(dist_om1,4,diss=TRUE)
pamclust5 <- pam(dist_om1,5,diss=TRUE)
pamclust6 <- pam(dist_om1,6,diss=TRUE)
pamclust7 <- pam(dist_om1,7,diss=TRUE)



write.table(data.frame(all_data$SID,pamclust3$clustering,pamclust4$clustering,pamclust5$clustering,pamclust6$clustering,pamclust7$clustering,all_data[,2:515]),file=paste(base_filename,'_3-7TYPES.TXT',sep=''),sep="|")
pdf(paste(base_filename,'_PAMPLOTS_ACT.PDF',sep=''),width=10.5,height=8)
seqdplot(seq_act_NA, group = pamclust3$clustering, border = NA, with.missing=TRUE)
seqdplot(seq_act_NA, group = pamclust4$clustering, border = NA, with.missing=TRUE)
seqdplot(seq_act_NA, group = pamclust5$clustering, border = NA, with.missing=TRUE)
seqdplot(seq_act_NA, group = pamclust6$clustering, border = NA, with.missing=TRUE)
seqdplot(seq_act_NA, group = pamclust7$clustering, border = NA, with.missing=TRUE)
seqiplot(seq_act, group = pamclust3$clustering, border = NA,tlim=1:50)
seqiplot(seq_act, group = pamclust4$clustering, border = NA,tlim=1:50)
seqiplot(seq_act, group = pamclust5$clustering, border = NA,tlim=1:50)
seqiplot(seq_act, group = pamclust6$clustering, border = NA,tlim=1:50)
seqiplot(seq_act, group = pamclust7$clustering, border = NA,tlim=1:50)
dev.off()

pdf(paste(base_filename,'_PAMPLOTS_CLIC.PDF',sep=''),width=10.5,height=8)
seqdplot(seq_clic_NA, group = pamclust3$clustering, border = NA, with.missing=TRUE)
seqdplot(seq_clic_NA, group = pamclust4$clustering, border = NA, with.missing=TRUE)
seqdplot(seq_clic_NA, group = pamclust5$clustering, border = NA, with.missing=TRUE)
seqdplot(seq_clic_NA, group = pamclust6$clustering, border = NA, with.missing=TRUE)
seqdplot(seq_clic_NA, group = pamclust7$clustering, border = NA, with.missing=TRUE)
seqiplot(seq_clic, group = pamclust3$clustering, border = NA,tlim=1:50)
seqiplot(seq_clic, group = pamclust4$clustering, border = NA,tlim=1:50)
seqiplot(seq_clic, group = pamclust5$clustering, border = NA,tlim=1:50)
seqiplot(seq_clic, group = pamclust6$clustering, border = NA,tlim=1:50)
seqiplot(seq_clic, group = pamclust7$clustering, border = NA,tlim=1:50)
dev.off()